---
scale: 1.0
marker_size: 14
panel_width: 114
panel_height: 181
name_display:
  show: false
  font_size: 8
  font_family: ''
  font_weight: bold
  max_length: 30
  mode: noun
hp_bar:
  height: 4
  width: 100
  show_text: false
  show_percentage: false
  text_style: overlay
  font_size: 8
  ranges:
    low:
      min: 0
      max: 33
    mid:
      min: 34
      max: 66
    high:
      min: 67
      max: 100
  show_hp_prefix: false
  show_numbers: true
  show: true
  show_bar: true
  text_position: bottom
status:
  show: true
  font_size: 8
body_parts:
  head:
  - 54
  - 15
  neck:
  - 54
  - 31
  chest:
  - 54
  - 46
  abdomen:
  - 53
  - 64
  back:
  - 0
  - 138
  leftArm:
  - 72
  - 44
  rightArm:
  - 37
  - 43
  leftHand:
  - 74
  - 80
  rightHand:
  - 31
  - 78
  leftLeg:
  - 60
  - 92
  rightLeg:
  - 45
  - 101
  leftFoot:
  - 60
  - 125
  rightFoot:
  - 47
  - 133
  leftEye:
  - 84
  - 0
  rightEye:
  - 3
  - 1
  nerves:
  - 87
  - 138
