---
scale: 1.0
marker_size: 14
panel_width: 114
panel_height: 181
name_display:
  show: false
  font_size: 8
  font_family: ''
  font_weight: bold
  max_length: 30
  mode: noun
hp_bar:
  height: 4
  width: 100
  show_text: false
  show_percentage: false
  text_style: overlay
  font_size: 8
  ranges:
    low:
      min: 0
      max: 33
    mid:
      min: 34
      max: 66
    high:
      min: 67
      max: 100
  show_hp_prefix: false
  show_numbers: true
  show: true
  show_bar: true
  text_position: bottom
status:
  show: true
  font_size: 8
body_parts:
  head:
  - 47
  - 27
  neck:
  - 48
  - 36
  chest:
  - 47
  - 49
  abdomen:
  - 47
  - 67
  back:
  - -1
  - 139
  leftArm:
  - 62
  - 49
  rightArm:
  - 30
  - 44
  leftHand:
  - 68
  - 80
  rightHand:
  - 25
  - 83
  leftLeg:
  - 57
  - 90
  rightLeg:
  - 39
  - 90
  leftFoot:
  - 60
  - 116
  rightFoot:
  - 31
  - 119
  leftEye:
  - 83
  - -1
  rightEye:
  - 3
  - 1
  nerves:
  - 87
  - 139
