---
scale: 1.0
marker_size: 14
panel_width: 114
panel_height: 181
name_display:
  show: false
  font_size: 8
  font_family: ''
  font_weight: bold
  max_length: 30
  mode: noun
hp_bar:
  height: 4
  width: 100
  show_text: false
  show_percentage: false
  text_style: overlay
  font_size: 8
  ranges:
    low:
      min: 0
      max: 33
    mid:
      min: 34
      max: 66
    high:
      min: 67
      max: 100
  show_hp_prefix: false
  show_numbers: true
  show: true
  show_bar: true
  text_position: bottom
status:
  show: true
  font_size: 8
body_parts:
  head:
  - 44
  - 12
  neck:
  - 44
  - 26
  chest:
  - 47
  - 37
  abdomen:
  - 45
  - 55
  back:
  - -2
  - 137
  leftArm:
  - 58
  - 30
  rightArm:
  - 29
  - 31
  leftHand:
  - 61
  - 61
  rightHand:
  - 22
  - 69
  leftLeg:
  - 53
  - 73
  rightLeg:
  - 38
  - 76
  leftFoot:
  - 59
  - 95
  rightFoot:
  - 31
  - 99
  leftEye:
  - 83
  - -3
  rightEye:
  - 3
  - -1
  nerves:
  - 86
  - 137
