---
scale: 0.7
marker_size: 10
panel_width: 89
panel_height: 136
name_display:
  show: false
  font_size: 8
  font_weight: normal
  mode: name
hp_bar:
  show: true
  show_bar: true
  text_style: overlay
  show_text: false
  text_position: top
  show_hp_prefix: true
  show_numbers: true
  show_percentage: true
  width: 75
  height: 4
  font_size: 8
status:
  show: true
  font_size: 8
body_parts:
  head:
  - 44
  - 9
  neck:
  - 43
  - 26
  chest:
  - 44
  - 42
  abdomen:
  - 47
  - 60
  back:
  - -1
  - 137
  leftArm:
  - 55
  - 38
  rightArm:
  - 29
  - 35
  leftHand:
  - 73
  - 53
  rightHand:
  - 32
  - 53
  leftLeg:
  - 53
  - 85
  rightLeg:
  - 33
  - 94
  leftFoot:
  - 52
  - 124
  rightFoot:
  - 36
  - 128
  leftEye:
  - 84
  - 0
  rightEye:
  - 3
  - 1
  nerves:
  - 87
  - 138
