---
scale: 1.0
marker_size: 14
panel_width: 114
panel_height: 181
name_display:
  show: false
  font_size: 8
  font_family: ''
  font_weight: bold
  max_length: 30
  mode: noun
hp_bar:
  height: 4
  width: 100
  show_text: false
  show_percentage: false
  text_style: overlay
  font_size: 8
  ranges:
    low:
      min: 0
      max: 33
    mid:
      min: 34
      max: 66
    high:
      min: 67
      max: 100
  show_hp_prefix: false
  show_numbers: true
  show: true
  show_bar: true
  text_position: bottom
status:
  show: true
  font_size: 8
body_parts:
  head:
  - 40
  - 4
  neck:
  - 41
  - 15
  chest:
  - 41
  - 36
  abdomen:
  - 43
  - 60
  back:
  - -1
  - 138
  leftArm:
  - 71
  - 39
  rightArm:
  - 21
  - 38
  leftHand:
  - 77
  - 80
  rightHand:
  - 6
  - 78
  leftLeg:
  - 58
  - 90
  rightLeg:
  - 31
  - 81
  leftFoot:
  - 66
  - 123
  rightFoot:
  - 27
  - 117
  leftEye:
  - 84
  - 0
  rightEye:
  - 4
  - 0
  nerves:
  - 87
  - 139
