---
scale: 0.7
marker_size: 10
panel_width: 89
panel_height: 136
name_display:
  show: false
  font_size: 8
  font_weight: normal
  mode: name
hp_bar:
  show: true
  show_bar: true
  text_style: overlay
  show_text: false
  text_position: top
  show_hp_prefix: true
  show_numbers: true
  show_percentage: true
  width: 75
  height: 4
  font_size: 8
status:
  show: true
  font_size: 8
body_parts:
  head:
  - 40
  - 4
  neck:
  - 41
  - 15
  chest:
  - 41
  - 36
  abdomen:
  - 43
  - 60
  back:
  - -1
  - 138
  leftArm:
  - 71
  - 39
  rightArm:
  - 21
  - 38
  leftHand:
  - 77
  - 80
  rightHand:
  - 6
  - 78
  leftLeg:
  - 58
  - 90
  rightLeg:
  - 31
  - 81
  leftFoot:
  - 66
  - 123
  rightFoot:
  - 27
  - 117
  leftEye:
  - 84
  - 0
  rightEye:
  - 4
  - 0
  nerves:
  - 87
  - 139
