---
scale: 0.7
marker_size: 10
panel_width: 89
panel_height: 136
name_display:
  show: false
  font_size: 8
  font_weight: normal
  mode: name
hp_bar:
  show: true
  show_bar: true
  text_style: overlay
  show_text: false
  text_position: top
  show_hp_prefix: true
  show_numbers: true
  show_percentage: true
  width: 75
  height: 4
  font_size: 8
status:
  show: true
  font_size: 8
body_parts:
  head:
  - 40
  - 29
  neck:
  - 52
  - 42
  chest:
  - 50
  - 57
  abdomen:
  - 31
  - 93
  back:
  - -1
  - 139
  leftArm:
  - 61
  - 72
  rightArm:
  - 42
  - 66
  leftHand:
  - 69
  - 88
  rightHand:
  - 53
  - 82
  leftLeg:
  - 40
  - 98
  rightLeg:
  - 15
  - 103
  leftFoot:
  - 38
  - 117
  rightFoot:
  - 12
  - 126
  leftEye:
  - 83
  - 0
  rightEye:
  - 4
  - 1
  nerves:
  - 87
  - 139
