---
scale: 0.7
marker_size: 10
panel_width: 89
panel_height: 136
name_display:
  show: false
  font_size: 8
  font_weight: normal
  mode: name
hp_bar:
  show: true
  show_bar: true
  text_style: overlay
  show_text: false
  text_position: top
  show_hp_prefix: true
  show_numbers: true
  show_percentage: true
  width: 75
  height: 4
  font_size: 8
status:
  show: true
  font_size: 8
body_parts:
  head:
  - 49
  - 6
  neck:
  - 53
  - 20
  chest:
  - 44
  - 33
  abdomen:
  - 43
  - 51
  back:
  - -1
  - 138
  leftArm:
  - 66
  - 36
  rightArm:
  - 22
  - 31
  leftHand:
  - 80
  - 23
  rightHand:
  - 14
  - 14
  leftLeg:
  - 63
  - 79
  rightLeg:
  - 28
  - 85
  leftFoot:
  - 66
  - 116
  rightFoot:
  - 14
  - 121
  leftEye:
  - 83
  - 0
  rightEye:
  - 4
  - -1
  nerves:
  - 87
  - 138
