---
scale: 0.7
marker_size: 10
panel_width: 89
panel_height: 136
name_display:
  show: false
  font_size: 8
  font_weight: normal
  mode: name
hp_bar:
  show: true
  show_bar: true
  text_style: overlay
  show_text: false
  text_position: top
  show_hp_prefix: true
  show_numbers: true
  show_percentage: true
  width: 75
  height: 4
  font_size: 8
status:
  show: true
  font_size: 8
body_parts:
  head:
  - 50
  - 17
  neck:
  - 50
  - 31
  chest:
  - 44
  - 48
  abdomen:
  - 38
  - 66
  back:
  - -1
  - 139
  leftArm:
  - 61
  - 51
  rightArm:
  - 22
  - 49
  leftHand:
  - 73
  - 52
  rightHand:
  - 16
  - 79
  leftLeg:
  - 57
  - 83
  rightLeg:
  - 25
  - 96
  leftFoot:
  - 62
  - 121
  rightFoot:
  - 11
  - 126
  leftEye:
  - 83
  - -2
  rightEye:
  - 5
  - -1
  nerves:
  - 87
  - 138
