---
scale: 0.7
marker_size: 10
panel_width: 89
panel_height: 136
name_display:
  show: false
  font_size: 8
  font_weight: normal
  mode: name
hp_bar:
  show: true
  show_bar: true
  text_style: overlay
  show_text: false
  text_position: top
  show_hp_prefix: true
  show_numbers: true
  show_percentage: true
  width: 75
  height: 4
  font_size: 8
status:
  show: true
  font_size: 8
body_parts:
  head:
  - 44
  - 4
  neck:
  - 44
  - 19
  chest:
  - 42
  - 37
  abdomen:
  - 43
  - 52
  back:
  - -1
  - 139
  leftArm:
  - 54
  - 34
  rightArm:
  - 29
  - 34
  leftHand:
  - 71
  - 62
  rightHand:
  - 19
  - 58
  leftLeg:
  - 56
  - 67
  rightLeg:
  - 39
  - 75
  leftFoot:
  - 59
  - 95
  rightFoot:
  - 45
  - 94
  leftEye:
  - 82
  - -2
  rightEye:
  - 3
  - -1
  nerves:
  - 87
  - 138
