---
scale: 1.0
marker_size: 14
panel_width: 114
panel_height: 181
name_display:
  show: false
  font_size: 8
  font_family: ''
  font_weight: bold
  max_length: 30
  mode: noun
hp_bar:
  height: 4
  width: 100
  show_text: false
  show_percentage: false
  text_style: overlay
  font_size: 8
  ranges:
    low:
      min: 0
      max: 33
    mid:
      min: 34
      max: 66
    high:
      min: 67
      max: 100
  show_hp_prefix: false
  show_numbers: true
  show: true
  show_bar: true
  text_position: bottom
status:
  show: true
  font_size: 8
body_parts:
  head:
  - 29
  - 14
  neck:
  - 31
  - 32
  chest:
  - 44
  - 38
  abdomen:
  - 41
  - 50
  back:
  - -3
  - 138
  leftArm:
  - 62
  - 28
  rightArm:
  - 17
  - 40
  leftHand:
  - 82
  - 72
  rightHand:
  - 5
  - 71
  leftLeg:
  - 61
  - 85
  rightLeg:
  - 25
  - 86
  leftFoot:
  - 60
  - 112
  rightFoot:
  - 17
  - 118
  leftEye:
  - 83
  - -1
  rightEye:
  - 3
  - -1
  nerves:
  - 87
  - 138
