---
scale: 0.7
marker_size: 10
panel_width: 89
panel_height: 136
name_display:
  show: false
  font_size: 8
  font_weight: normal
  mode: name
hp_bar:
  show: true
  show_bar: true
  text_style: overlay
  show_text: false
  text_position: top
  show_hp_prefix: true
  show_numbers: true
  show_percentage: true
  width: 75
  height: 4
  font_size: 8
status:
  show: true
  font_size: 8
body_parts:
  head:
  - 43
  - 44
  neck:
  - 43
  - 57
  chest:
  - 43
  - 68
  abdomen:
  - 45
  - 81
  back:
  - 0
  - 138
  leftArm:
  - 57
  - 73
  rightArm:
  - 30
  - 74
  leftHand:
  - 65
  - 92
  rightHand:
  - 21
  - 94
  leftLeg:
  - 73
  - 69
  rightLeg:
  - 14
  - 72
  leftFoot:
  - 81
  - 103
  rightFoot:
  - 8
  - 104
  leftEye:
  - 84
  - 1
  rightEye:
  - 3
  - -2
  nerves:
  - 88
  - 138
