---
scale: 1.0
marker_size: 14
panel_width: 114
panel_height: 181
name_display:
  show: false
  font_size: 8
  font_family: ''
  font_weight: bold
  max_length: 30
  mode: noun
hp_bar:
  height: 4
  width: 100
  show_text: false
  show_percentage: false
  text_style: overlay
  font_size: 8
  ranges:
    low:
      min: 0
      max: 33
    mid:
      min: 34
      max: 66
    high:
      min: 67
      max: 100
  show_hp_prefix: false
  show_numbers: true
  show: true
  show_bar: true
  text_position: bottom
status:
  show: true
  font_size: 8
body_parts:
  head:
  - 65
  - 11
  neck:
  - 69
  - 42
  chest:
  - 52
  - 47
  abdomen:
  - 41
  - 73
  back:
  - 0
  - 138
  leftArm:
  - 67
  - 60
  rightArm:
  - 38
  - 56
  leftHand:
  - 84
  - 72
  rightHand:
  - 63
  - 76
  leftLeg:
  - 56
  - 86
  rightLeg:
  - 35
  - 105
  leftFoot:
  - 72
  - 116
  rightFoot:
  - 7
  - 121
  leftEye:
  - 83
  - -5
  rightEye:
  - 2
  - -3
  nerves:
  - 86
  - 138
