---
scale: 0.7
marker_size: 10
panel_width: 89
panel_height: 136
name_display:
  show: false
  font_size: 8
  font_weight: normal
  mode: name
hp_bar:
  show: true
  show_bar: true
  text_style: overlay
  show_text: false
  text_position: top
  show_hp_prefix: true
  show_numbers: true
  show_percentage: true
  width: 75
  height: 4
  font_size: 8
status:
  show: true
  font_size: 8
body_parts:
  head:
  - 47
  - 3
  neck:
  - 47
  - 19
  chest:
  - 46
  - 35
  abdomen:
  - 48
  - 63
  back:
  - -1
  - 137
  leftArm:
  - 70
  - 43
  rightArm:
  - 19
  - 41
  leftHand:
  - 78
  - 79
  rightHand:
  - 17
  - 76
  leftLeg:
  - 62
  - 96
  rightLeg:
  - 29
  - 102
  leftFoot:
  - 62
  - 122
  rightFoot:
  - 24
  - 127
  leftEye:
  - 83
  - -1
  rightEye:
  - 2
  - 0
  nerves:
  - 86
  - 136
