---
scale: 1.0
marker_size: 14
panel_width: 114
panel_height: 181
name_display:
  show: false
  font_size: 8
  font_family: ''
  font_weight: bold
  max_length: 30
  mode: noun
hp_bar:
  height: 4
  width: 100
  show_text: false
  show_percentage: false
  text_style: overlay
  font_size: 8
  ranges:
    low:
      min: 0
      max: 33
    mid:
      min: 34
      max: 66
    high:
      min: 67
      max: 100
  show_hp_prefix: false
  show_numbers: true
  show: true
  show_bar: true
  text_position: bottom
status:
  show: true
  font_size: 8
body_parts:
  head:
  - 46
  - 3
  neck:
  - 47
  - 16
  chest:
  - 48
  - 33
  abdomen:
  - 49
  - 56
  back:
  - 0
  - 138
  leftArm:
  - 65
  - 37
  rightArm:
  - 21
  - 32
  leftHand:
  - 72
  - 77
  rightHand:
  - 17
  - 73
  leftLeg:
  - 55
  - 83
  rightLeg:
  - 34
  - 83
  leftFoot:
  - 61
  - 122
  rightFoot:
  - 21
  - 128
  leftEye:
  - 83
  - -1
  rightEye:
  - 4
  - -1
  nerves:
  - 86
  - 137
