---
scale: 0.7
marker_size: 10
panel_width: 89
panel_height: 136
name_display:
  show: false
  font_size: 8
  font_weight: normal
  mode: name
hp_bar:
  show: true
  show_bar: true
  text_style: overlay
  show_text: false
  text_position: top
  show_hp_prefix: true
  show_numbers: true
  show_percentage: true
  width: 75
  height: 4
  font_size: 8
status:
  show: true
  font_size: 8
body_parts:
  head:
  - 22
  - 32
  neck:
  - 33
  - 49
  chest:
  - 59
  - 54
  abdomen:
  - 37
  - 100
  back:
  - -1
  - 139
  leftArm:
  - 47
  - 80
  rightArm:
  - 19
  - 82
  leftHand:
  - 64
  - 82
  rightHand:
  - 2
  - 97
  leftLeg:
  - 58
  - 106
  rightLeg:
  - 29
  - 112
  leftFoot:
  - 84
  - 106
  rightFoot:
  - 44
  - 126
  leftEye:
  - 83
  - -3
  rightEye:
  - 4
  - -1
  nerves:
  - 87
  - 139
