---
scale: 0.7
marker_size: 10
panel_width: 89
panel_height: 136
name_display:
  show: false
  font_size: 8
  font_weight: normal
  mode: name
hp_bar:
  show: true
  show_bar: true
  text_style: overlay
  show_text: false
  text_position: top
  show_hp_prefix: true
  show_numbers: true
  show_percentage: true
  width: 75
  height: 4
  font_size: 8
status:
  show: true
  font_size: 8
body_parts:
  head:
  - 23
  - 39
  neck:
  - 21
  - 59
  chest:
  - 41
  - 58
  abdomen:
  - 60
  - 65
  back:
  - -1
  - 138
  leftArm:
  - 34
  - 84
  rightArm:
  - 14
  - 81
  leftHand:
  - 22
  - 99
  rightHand:
  - 4
  - 107
  leftLeg:
  - 72
  - 88
  rightLeg:
  - 53
  - 87
  leftFoot:
  - 83
  - 112
  rightFoot:
  - 67
  - 110
  leftEye:
  - 84
  - 1
  rightEye:
  - 4
  - 0
  nerves:
  - 87
  - 139
