---
scale: 0.7
marker_size: 10
panel_width: 89
panel_height: 136
name_display:
  show: false
  font_size: 8
  font_weight: normal
  mode: name
hp_bar:
  show: true
  show_bar: true
  text_style: overlay
  show_text: false
  text_position: top
  show_hp_prefix: true
  show_numbers: true
  show_percentage: true
  width: 75
  height: 4
  font_size: 8
status:
  show: true
  font_size: 8
body_parts:
  head:
  - 35
  - 81
  neck:
  - 37
  - 95
  chest:
  - 44
  - 68
  abdomen:
  - 53
  - 44
  back:
  - -2
  - 139
  leftArm:
  - 53
  - 86
  rightArm:
  - 21
  - 81
  leftHand:
  - 48
  - 116
  rightHand:
  - 9
  - 110
  leftLeg:
  - 71
  - 82
  rightLeg:
  - 65
  - 92
  leftFoot:
  - 87
  - 97
  rightFoot:
  - 73
  - 105
  leftEye:
  - 83
  - -1
  rightEye:
  - 3
  - 1
  nerves:
  - 87
  - 138
