---
scale: 0.7
marker_size: 10
panel_width: 89
panel_height: 136
name_display:
  show: false
  font_size: 8
  font_weight: normal
  mode: name
hp_bar:
  show: true
  show_bar: true
  text_style: overlay
  show_text: false
  text_position: top
  show_hp_prefix: true
  show_numbers: true
  show_percentage: true
  width: 75
  height: 4
  font_size: 8
status:
  show: true
  font_size: 8
body_parts:
  head:
  - 76
  - 23
  neck:
  - 73
  - 33
  chest:
  - 56
  - 56
  abdomen:
  - 32
  - 72
  back:
  - -2
  - 139
  leftArm:
  - 73
  - 49
  rightArm:
  - 62
  - 58
  leftHand:
  - 84
  - 56
  rightHand:
  - 73
  - 66
  leftLeg:
  - 59
  - 72
  rightLeg:
  - 40
  - 87
  leftFoot:
  - 80
  - 116
  rightFoot:
  - 33
  - 129
  leftEye:
  - 83
  - -1
  rightEye:
  - 4
  - -1
  nerves:
  - 87
  - 138
