---
scale: 1.0
marker_size: 14
panel_width: 114
panel_height: 181
name_display:
  show: false
  font_size: 8
  font_family: ''
  font_weight: bold
  max_length: 30
  mode: noun
hp_bar:
  height: 4
  width: 100
  show_text: false
  show_percentage: false
  text_style: overlay
  font_size: 8
  ranges:
    low:
      min: 0
      max: 33
    mid:
      min: 34
      max: 66
    high:
      min: 67
      max: 100
  show_hp_prefix: false
  show_numbers: true
  show: true
  show_bar: true
  text_position: bottom
status:
  show: true
  font_size: 8
body_parts:
  head:
  - 7
  - 23
  neck:
  - 17
  - 39
  chest:
  - 32
  - 46
  abdomen:
  - 55
  - 54
  back:
  - -1
  - 138
  leftArm:
  - 42
  - 60
  rightArm:
  - 26
  - 59
  leftHand:
  - 44
  - 105
  rightHand:
  - 16
  - 90
  leftLeg:
  - 61
  - 82
  rightLeg:
  - 32
  - 87
  leftFoot:
  - 56
  - 120
  rightFoot:
  - 11
  - 130
  leftEye:
  - 84
  - -1
  rightEye:
  - 4
  - 0
  nerves:
  - 87
  - 138
