---
scale: 1.0
marker_size: 14
panel_width: 114
panel_height: 181
name_display:
  show: false
  font_size: 8
  font_family: ''
  font_weight: bold
  max_length: 30
  mode: noun
hp_bar:
  height: 4
  width: 100
  show_text: false
  show_percentage: false
  text_style: overlay
  font_size: 8
  ranges:
    low:
      min: 0
      max: 33
    mid:
      min: 34
      max: 66
    high:
      min: 67
      max: 100
  show_hp_prefix: false
  show_numbers: true
  show: true
  show_bar: true
  text_position: bottom
status:
  show: true
  font_size: 8
body_parts:
  head:
  - 43
  - 1
  neck:
  - 42
  - 18
  chest:
  - 42
  - 39
  abdomen:
  - 42
  - 62
  back:
  - -3
  - 137
  leftArm:
  - 63
  - 38
  rightArm:
  - 23
  - 36
  leftHand:
  - 67
  - 76
  rightHand:
  - 17
  - 76
  leftLeg:
  - 54
  - 90
  rightLeg:
  - 32
  - 95
  leftFoot:
  - 58
  - 133
  rightFoot:
  - 27
  - 133
  leftEye:
  - 83
  - -3
  rightEye:
  - 3
  - -2
  nerves:
  - 86
  - 138
